config/routes.rb
Rails.application.routes.draw do
  resources :iscrivitis
  resources :iscriziones
  resources :cavallis
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/index', to: 'home#index', as: 'index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cavalli.rb
class Cavalli < ApplicationRecord
end

app/models/iscriviti.rb
class Iscriviti < ApplicationRecord
end

app/models/iscrizione.rb
class Iscrizione < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/cavallis_controller.rb
class CavallisController < ApplicationController
  before_action :set_cavalli, only: %i[ show edit update destroy ]

  # GET /cavallis or /cavallis.json
  def index
    @cavallis = Cavalli.all
  end

  # GET /cavallis/1 or /cavallis/1.json
  def show
  end

  # GET /cavallis/new
  def new
    @cavalli = Cavalli.new
  end

  # GET /cavallis/1/edit
  def edit
  end

  # POST /cavallis or /cavallis.json
  def create
    @cavalli = Cavalli.new(cavalli_params)

    respond_to do |format|
      if @cavalli.save
        format.html { redirect_to @cavalli, notice: "Cavalli was successfully created." }
        format.json { render :show, status: :created, location: @cavalli }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cavalli.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cavallis/1 or /cavallis/1.json
  def update
    respond_to do |format|
      if @cavalli.update(cavalli_params)
        format.html { redirect_to @cavalli, notice: "Cavalli was successfully updated." }
        format.json { render :show, status: :ok, location: @cavalli }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cavalli.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cavallis/1 or /cavallis/1.json
  def destroy
    @cavalli.destroy
    respond_to do |format|
      format.html { redirect_to cavallis_url, notice: "Cavalli was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cavalli
      @cavalli = Cavalli.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cavalli_params
      params.require(:cavalli).permit(:nome, :descrizione, :età)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/iscrivitis_controller.rb
class IscrivitisController < ApplicationController
  before_action :set_iscriviti, only: %i[ show edit update destroy ]

  # GET /iscrivitis or /iscrivitis.json
  def index
    @iscrivitis = Iscriviti.all
  end

  # GET /iscrivitis/1 or /iscrivitis/1.json
  def show
  end

  # GET /iscrivitis/new
  def new
    @iscriviti = Iscriviti.new
  end

  # GET /iscrivitis/1/edit
  def edit
  end

  # POST /iscrivitis or /iscrivitis.json
  def create
    @iscriviti = Iscriviti.new(iscriviti_params)

    respond_to do |format|
      if @iscriviti.save
        format.html { redirect_to @iscriviti, notice: "Iscriviti was successfully created." }
        format.json { render :show, status: :created, location: @iscriviti }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @iscriviti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iscrivitis/1 or /iscrivitis/1.json
  def update
    respond_to do |format|
      if @iscriviti.update(iscriviti_params)
        format.html { redirect_to @iscriviti, notice: "Iscriviti was successfully updated." }
        format.json { render :show, status: :ok, location: @iscriviti }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @iscriviti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iscrivitis/1 or /iscrivitis/1.json
  def destroy
    @iscriviti.destroy
    respond_to do |format|
      format.html { redirect_to iscrivitis_url, notice: "Iscriviti was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iscriviti
      @iscriviti = Iscriviti.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def iscriviti_params
      params.require(:iscriviti).permit(:cognome, :nome, :email, :cellulare, :età, :richiesta)
    end
end

app/controllers/iscriziones_controller.rb
class IscrizionesController < ApplicationController
  before_action :set_iscrizione, only: %i[ show edit update destroy ]

  # GET /iscriziones or /iscriziones.json
  def index
    @iscriziones = Iscrizione.all
  end

  # GET /iscriziones/1 or /iscriziones/1.json
  def show
  end

  # GET /iscriziones/new
  def new
    @iscrizione = Iscrizione.new
  end

  # GET /iscriziones/1/edit
  def edit
  end

  # POST /iscriziones or /iscriziones.json
  def create
    @iscrizione = Iscrizione.new(iscrizione_params)

    respond_to do |format|
      if @iscrizione.save
        format.html { redirect_to @iscrizione, notice: "Iscrizione was successfully created." }
        format.json { render :show, status: :created, location: @iscrizione }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @iscrizione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iscriziones/1 or /iscriziones/1.json
  def update
    respond_to do |format|
      if @iscrizione.update(iscrizione_params)
        format.html { redirect_to @iscrizione, notice: "Iscrizione was successfully updated." }
        format.json { render :show, status: :ok, location: @iscrizione }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @iscrizione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iscriziones/1 or /iscriziones/1.json
  def destroy
    @iscrizione.destroy
    respond_to do |format|
      format.html { redirect_to iscriziones_url, notice: "Iscrizione was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iscrizione
      @iscrizione = Iscrizione.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def iscrizione_params
      params.require(:iscrizione).permit(:cognome, :nome, :email, :email, :cellulare, :età, :richiesta)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cavallis_helper.rb
module CavallisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iscrivitis_helper.rb
module IscrivitisHelper
end

app/helpers/iscriziones_helper.rb
module IscrizionesHelper
end

app/views/cavallis/_form.html.erb
<%= form_with(model: cavalli) do |form| %>
  <% if cavalli.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cavalli.errors.count, "error") %> prohibited this cavalli from being saved:</h2>

      <ul>
        <% cavalli.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:'form-control bg-dark mioform ' %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_field :descrizione, class:'form-control bg-dark mioform ' %>
  </div>

  <div class="field">
    <%= form.label :età %>
    <%= form.number_field :età, class:'form-control bg-dark mioform ' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cavallis/edit.html.erb
<h1>Editing Cavalli</h1>

<%= render 'form', cavalli: @cavalli %>

<%= link_to 'Show', @cavalli %> |
<%= link_to 'Back', cavallis_path %>

app/views/cavallis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cavallis</h1>

<table class='table table-expand-lg table-dark bg-dark  '>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrizione</th>
      <th>Età</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cavallis.each do |cavalli| %>
      <tr>
        <td><%= cavalli.nome %></td>
        <td><%= cavalli.descrizione %></td>
        <td><%= cavalli.età %></td>
        <td><%= link_to 'Show', cavalli %></td>
        <td><%= link_to 'Edit', edit_cavalli_path(cavalli) %></td>
        <td><%= link_to 'Destroy', cavalli, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cavalli', new_cavalli_path %>

app/views/cavallis/new.html.erb
<h1>New Cavalli</h1>

<%= render 'form', cavalli: @cavalli %>

<%= link_to 'Back', cavallis_path %>

app/views/cavallis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cavalli.nome %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @cavalli.descrizione %>
</p>

<p>
  <strong>Età:</strong>
  <%= @cavalli.età %>
</p>

<%= link_to 'Edit', edit_cavalli_path(@cavalli) %> |
<%= link_to 'Back', cavallis_path %>

app/views/iscrivitis/_form.html.erb
<%= form_with(model: iscriviti) do |form| %>
  <% if iscriviti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iscriviti.errors.count, "error") %> prohibited this iscriviti from being saved:</h2>

      <ul>
        <% iscriviti.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cognome %>
    <%= form.text_field :cognome %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cellulare %>
    <%= form.text_field :cellulare %>
  </div>

  <div class="field">
    <%= form.label :età %>
    <%= form.number_field :età %>
  </div>

  <div class="field">
    <%= form.label :richiesta %>
    <%= form.text_field :richiesta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/iscrivitis/edit.html.erb
<h1>Editing Iscriviti</h1>

<%= render 'form', iscriviti: @iscriviti %>

<%= link_to 'Show', @iscriviti %> |
<%= link_to 'Back', iscrivitis_path %>

app/views/iscrivitis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Iscrivitis</h1>

<table>
  <thead>
    <tr>
      <th>Cognome</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Cellulare</th>
      <th>Età</th>
      <th>Richiesta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iscrivitis.each do |iscriviti| %>
      <tr>
        <td><%= iscriviti.cognome %></td>
        <td><%= iscriviti.nome %></td>
        <td><%= iscriviti.email %></td>
        <td><%= iscriviti.cellulare %></td>
        <td><%= iscriviti.età %></td>
        <td><%= iscriviti.richiesta %></td>
        <td><%= link_to 'Show', iscriviti %></td>
        <td><%= link_to 'Edit', edit_iscriviti_path(iscriviti) %></td>
        <td><%= link_to 'Destroy', iscriviti, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iscriviti', new_iscriviti_path %>

app/views/iscrivitis/new.html.erb
<h1>New Iscriviti</h1>

<%= render 'form', iscriviti: @iscriviti %>

<%= link_to 'Back', iscrivitis_path %>

app/views/iscrivitis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cognome:</strong>
  <%= @iscriviti.cognome %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @iscriviti.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @iscriviti.email %>
</p>

<p>
  <strong>Cellulare:</strong>
  <%= @iscriviti.cellulare %>
</p>

<p>
  <strong>Età:</strong>
  <%= @iscriviti.età %>
</p>

<p>
  <strong>Richiesta:</strong>
  <%= @iscriviti.richiesta %>
</p>

<%= link_to 'Edit', edit_iscriviti_path(@iscriviti) %> |
<%= link_to 'Back', iscrivitis_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Cioccolateria</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/index">Maneggio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/cavallis">Cavalli</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/iscriziones">Iscrizione</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>


  <br>

    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

  </body>
</html>